(in-package :mu-cl-resources)

(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "ext"  "http://mu.semte.ch/vocabularies/ext/")

(define-resource user ()
  :class (s-prefix "foaf:Person")
  :properties `((:name  :string ,(s-prefix "foaf:name"))
                (:email :string ,(s-prefix "foaf:mbox")))
  :resource-base (s-url "http://tinto.app/users/")
  :on-path "users")

(define-resource group ()
  :class (s-prefix "foaf:Organization")
  :properties `((:name   :string ,(s-prefix "foaf:name"))
                (:status :string ,(s-prefix "ext:status")))
  :has-many `((member :via ,(s-prefix "foaf:member")
                      :as "members"))
  :resource-base (s-url "http://tinto.app/groups/")
  :on-path "groups")

(define-resource weekly-count ()
  :class (s-prefix "ext:WeeklyCount")
  :properties `((:period :string  ,(s-prefix "ext:period"))
                (:count  :integer ,(s-prefix "ext:count")))
  :has-one `((user :via ,(s-prefix "ext:user")
                   :as "user"))
  :resource-base (s-url "http://tinto.app/weekly-counts/")
  :on-path "weekly-counts")
